#! /bin/sh

###############
## autostart ##
###############

function autostart {
    ## sometimes sxhkd doesn't obey the reload command
    ## so kill him, and show him who is the boss
    pkill sxhkd
    sxhkd &
    
    ## start polybar, the best invention in the ricing world
    pkill polybar
    polybar -c ~/.config/polybar/config arch &
    
    ## set the wallpaper
    feh --bg-fill ~/.config/bspwm/wallpaper/wallpaper.png
    
    ## reload compton
    pkill compton
    compton -b &
    
    ## reload the cursor theme
    xsetroot -cursor_name left_ptr
    
    ## other program
    fcitx &
    volumeicon &
}

## only run autostart when bspwm first load
if [ $1 == "reload" ]
then
    echo "bspwm is runnning, reload now"
else
    autostart
    ## wait for all programs finishing start
    ## aimming to solve strange padding problem
    sleep 5

fi


###################
## configuration ##
###################

## workspace name
bspc monitor -d I II III IV V VI VII VIII IX X

## common bspwm configuration
#bspc config border_width 2
#bspc config window_gap 12
bspc config window_gap 16
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

## color settings
bspc config focused_border_color "#2f343f" 
bspc config normal_border_color "#2f343f"
bspc config border_width 3

## set new window appear right of the old window
bspc config initial_polarity second_child

##################
## window rules ##
##################

## workspace 1 (labs)
bspc rule -a Sakura desktop='^1' follow=on focus=on

## workspace 2 (web browsers)
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on

## workspace 3 (coding)
bspc rule -a Eclpise desktop='^3' follow=on focus=on
bspc rule -a Emacs desktop='^3' follow=on focus=on

## workspace 4 (text-editors)
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-base='^4' follow=on focus=on
bspc rule -a libreoffice-calc='^4' follow=on focus=on
bspc rule -a libreoffice-draw='^4' follow=on focus=on
bspc rule -a libreoffice-impress='^4' follow=on focus=on
bspc rule -a libreoffice-math='^4' follow=on focus=on
bspc rule -a libreoffice-writer='^4' follow=on focus=on

## workspace 5 (File)
bspc rule -a Nautilus desktop='^5' follow=on focus=on

# workspace 6 (multimedia)
bspc rule -a Audacity desktop='^6' follow=on focus=on
bspc rule -a Vlc desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Ghb desktop='^6' follow=on focus=on
bspc rule -a Xfburn desktop='^6' follow=on focus=on

## workspace 7 (graphics-editors)
#bspc rule -a Gimp desktop='^7' follow=on focus=on
#bspc rule -a Gimp-2.8 desktop='^7' follow=on focus=on
#bspc rule -a Inkscape desktop='^7' follow=on focus=on
#bspc rule -a Oomox desktop='^7' follow=on focus=on

## workspace 8 (system-settings)
#bspc rule -a Lxappearance desktop='^8' state=floating follow=on
#bspc rule -a Xfce4-settings-manager desktop='^8' state=floating follow=on
#bspc rule -a Lightdm-gtk-greeter-settings desktop='^8' state=floating follow=on
#bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on
#bspc rule -a Lxtask desktop='^8' state=floating follow=on
#bspc rule -a GParted desktop='^8' follow=on focus=on
#bspc rule -a Pavucontrol desktop='^8' state=floating follow=on
#bspc rule -a Exo-helper-1 desktop='^8' state=floating follow=on
#bspc rule -a Lxrandr desktop='^8' state=floating follow=on
#bspc rule -a Arandr desktop='^8' state=floating follow=on

## need to be floating
bspc rule -a feh state=floating follow=on
bspc rule -a mpv state=floating follow=on


